apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-config
data:
  master.setup: |
    CREATE FUNCTION one() RETURNS integer AS 'select 1;' LANGUAGE SQL;
    CREATE TABLE eventstore ( correlationid text );
    SELECT create_distributed_table('eventstore', 'correlationid');
    CREATE extension if not exists postgis;
    CREATE extension if not exists fuzzystrmatch;
    CREATE EXTENSION if not exists postgis_tiger_geocoder;
    ALTER SYSTEM SET max_connections = '1500';  
    ALTER SYSTEM SET shared_buffers = '1GB'; 
    ALTER SYSTEM SET maintenance_work_mem = '256MB'; 
    ALTER SYSTEM SET work_mem = '64MB';
    ALTER SYSTEM SET checkpoint_completion_target = '0.9';
    ALTER SYSTEM SET random_page_cost = '1.1';
    ALTER SYSTEM SET effective_io_concurrency = '300';
    ALTER SYSTEM SET min_wal_size = '1GB'; 
    ALTER SYSTEM SET max_wal_size = '4GB'; 
    ALTER SYSTEM SET synchronous_commit='remote_apply';
    set citus.shard_count = 64;
    SET citus.shard_replication_factor = 3;
  coordinator.setup: |
    CREATE FUNCTION one() RETURNS integer AS 'select 1;' LANGUAGE SQL;
  worker.setup: |
    CREATE FUNCTION two() RETURNS integer AS 'select 2;' LANGUAGE SQL;
    CREATE extension if not exists postgis;
    CREATE extension if not exists fuzzystrmatch;
    CREATE EXTENSION if not exists postgis_tiger_geocoder;